require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TroopTypesController do

  # This should return the minimal set of attributes required to create a valid
  # TroopType. As you add validations to TroopType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all troop_types as @troop_types" do
      troop_type = TroopType.create! valid_attributes
      get :index
      assigns(:troop_types).should eq([troop_type])
    end
  end

  describe "GET show" do
    it "assigns the requested troop_type as @troop_type" do
      troop_type = TroopType.create! valid_attributes
      get :show, :id => troop_type.id.to_s
      assigns(:troop_type).should eq(troop_type)
    end
  end

  describe "GET new" do
    it "assigns a new troop_type as @troop_type" do
      get :new
      assigns(:troop_type).should be_a_new(TroopType)
    end
  end

  describe "GET edit" do
    it "assigns the requested troop_type as @troop_type" do
      troop_type = TroopType.create! valid_attributes
      get :edit, :id => troop_type.id.to_s
      assigns(:troop_type).should eq(troop_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TroopType" do
        expect {
          post :create, :troop_type => valid_attributes
        }.to change(TroopType, :count).by(1)
      end

      it "assigns a newly created troop_type as @troop_type" do
        post :create, :troop_type => valid_attributes
        assigns(:troop_type).should be_a(TroopType)
        assigns(:troop_type).should be_persisted
      end

      it "redirects to the created troop_type" do
        post :create, :troop_type => valid_attributes
        response.should redirect_to(TroopType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved troop_type as @troop_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        TroopType.any_instance.stub(:save).and_return(false)
        post :create, :troop_type => {}
        assigns(:troop_type).should be_a_new(TroopType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TroopType.any_instance.stub(:save).and_return(false)
        post :create, :troop_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested troop_type" do
        troop_type = TroopType.create! valid_attributes
        # Assuming there are no other troop_types in the database, this
        # specifies that the TroopType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TroopType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => troop_type.id, :troop_type => {'these' => 'params'}
      end

      it "assigns the requested troop_type as @troop_type" do
        troop_type = TroopType.create! valid_attributes
        put :update, :id => troop_type.id, :troop_type => valid_attributes
        assigns(:troop_type).should eq(troop_type)
      end

      it "redirects to the troop_type" do
        troop_type = TroopType.create! valid_attributes
        put :update, :id => troop_type.id, :troop_type => valid_attributes
        response.should redirect_to(troop_type)
      end
    end

    describe "with invalid params" do
      it "assigns the troop_type as @troop_type" do
        troop_type = TroopType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TroopType.any_instance.stub(:save).and_return(false)
        put :update, :id => troop_type.id.to_s, :troop_type => {}
        assigns(:troop_type).should eq(troop_type)
      end

      it "re-renders the 'edit' template" do
        troop_type = TroopType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TroopType.any_instance.stub(:save).and_return(false)
        put :update, :id => troop_type.id.to_s, :troop_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested troop_type" do
      troop_type = TroopType.create! valid_attributes
      expect {
        delete :destroy, :id => troop_type.id.to_s
      }.to change(TroopType, :count).by(-1)
    end

    it "redirects to the troop_types list" do
      troop_type = TroopType.create! valid_attributes
      delete :destroy, :id => troop_type.id.to_s
      response.should redirect_to(troop_types_url)
    end
  end

end
